
export const styles = {
    appBar: {
        background: 'transparent',
        zIndex: 1100,
        '&::before': {
            content: '""',
            position: 'absolute',
            inset: 0,
            backdropFilter: 'blur(12px)',
            pointerEvents: 'none',
        },
    },
    toolbar: {
        maxWidth: 1400,
        mx: 'auto',
        width: '100%',
        justifyContent: 'space-between',
        py: 0.5,
        position: 'relative',
        zIndex: 1,
    },
    logo: {
        fontFamily: '"Cinzel", serif',
        fontWeight: 900,
        fontSize: '1.3rem',
        color: '#c4a44a',
        letterSpacing: '0.15em',
        textShadow: '0 0 20px rgba(196,164,74,0.3)',
        cursor: 'none',
    },
    navBox: {
        display: { xs: 'none', md: 'flex' },
        gap: 0.5,
    },
    navButton: {
        color: '#8a8580',
        fontSize: '0.75rem',
        fontWeight: 600,
        letterSpacing: '0.12em',
        textTransform: 'uppercase',
        px: 2,
        position: 'relative',
        transition: 'color 0.3s',
        '&:hover': { color: '#c4a44a', background: 'transparent' },
        '&::after': {
            content: '""',
            position: 'absolute',
            bottom: 4,
            left: '50%',
            width: 0,
            height: 1,
            background: '#c4a44a',
            transition: 'all 0.3s',
            transform: 'translateX(-50%)',
        },
        '&:hover::after': { width: '60%' },
    },
    actionsBox: {
        display: 'flex',
        alignItems: 'center',
        gap: 1,
    },
    playButton: {
        fontSize: '0.7rem',
        px: 2.5,
        py: 0.8,
        display: { xs: 'none', sm: 'flex' },
    },
}
